"""
PluginRuntime — контракт среды выполнения плагина (Protocol).

Только typing/Protocol. Никакой реализации.
Плагин получает opaque объект, удовлетворяющий этому контракту.
"""

from typing import Any, Awaitable, Callable, Optional, Protocol

from core.service.models import ServiceAuthConfig

class PluginAPI(Protocol):
    async def call_service(self, name: str, *args: Any, **kwargs: Any) -> Any: ...
    async def has_service(self, name: str) -> bool: ...
    async def publish_event(self, event_type: str, payload: dict[str, Any]) -> None: ...
    async def publish_operation_ready(self, operation_id: str, **extra: Any) -> None: ...
    async def register_service(
        self,
        name: str,
        func: Callable[..., Awaitable[Any]],
        *,
        resource: Optional[str] = None,
        admin_only: Optional[bool] = None,
        filter_result: bool = False,
        enforce_result: bool = False,
        preload_resource: Optional[
            Callable[[tuple[Any, ...], dict[str, Any]], Awaitable[Any]]
        ] = None,
        inject_owner_param: Optional[str] = None,
        version: Optional[str] = None,
        auth_config: Optional[ServiceAuthConfig] = None,
    ) -> None: ...
    async def unregister_service(self, name: str) -> None: ...
    def register_http(self, endpoint: Any) -> None: ...
    def register_operation_handler(self, op_type: str, handler: Any) -> None: ...
    async def storage_get(self, namespace: str, key: str) -> Any: ...
    async def storage_set(self, namespace: str, key: str, value: Any) -> None: ...
    async def storage_delete(self, namespace: str, key: str) -> bool: ...
    async def storage_list_keys(self, namespace: str) -> list[str]: ...


class PluginRuntime(Protocol):
    """
    Контракт runtime, передаваемого плагину.
    Core предоставляет объект, совместимый с этим протоколом.
    """

    # Legacy surfaces (kept for compatibility; new plugins should prefer methods below or runtime.api)
    service_registry: Any
    event_bus: Any
    storage: Any
    state: Any
    operations: Any
    api: PluginAPI

    async def call_service(self, name: str, *args: Any, **kwargs: Any) -> Any: ...
    async def has_service(self, name: str) -> bool: ...
    async def publish_event(self, event_type: str, payload: dict[str, Any]) -> None: ...
    async def publish_operation_ready(self, operation_id: str, **extra: Any) -> None: ...
    async def storage_get(self, namespace: str, key: str) -> Any: ...
    async def storage_set(self, namespace: str, key: str, value: Any) -> None: ...
    async def storage_delete(self, namespace: str, key: str) -> bool: ...
    async def storage_list_keys(self, namespace: str) -> list[str]: ...
